name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        make install

    - name: Download NLTK data
      run: |
        venv/bin/python -m nltk.downloader stopwords

    - name: Run the application
      run: |
        nohup make run &
        sleep 10

    # Test Flask 
    - name: Test if Flask server is running
      run: curl -f http://localhost:3000 || exit 1
